import type { Unit } from '../schemas/common';
import type { Allergen } from '../schemas/profile';
import type { FoodCategory, FoodDef, FoodDiet } from './types';

/*
 * Crumb's curated food table: per-100 g values as typically prepared.
 *
 * - `usda` rows use USDA FoodData Central (SR Legacy / FNDDS) values, public domain (CC0).
 * - `curated` rows are home-style Indian recipe estimates, cross-checked against published
 *   Indian composition data (ICMR-NIN IFCT 2017, Indian Nutrient Databank) and common
 *   household portions. They are deliberately "typical", and the app shows ranges around them.
 *
 * Unit weights are grams for ONE unit of that food (e.g. one roti ≈ 40 g, one katori dal ≈ 150 g).
 * Every row is checked by tests for Atwater consistency (4P + 4C + 9F + 7A ≈ kcal).
 */

interface Extra {
  jainAvoid?: boolean;
  allergens?: Allergen[];
  oilSensitive?: boolean;
  source?: 'usda' | 'curated';
  liquid?: boolean;
  alcoholG?: number;
}

function food(
  id: string,
  name: string,
  emoji: string,
  category: FoodCategory,
  diet: FoodDiet,
  macros: [kcal: number, proteinG: number, carbsG: number, fatG: number],
  units: Partial<Record<Unit, number>>,
  defaultUnit: Unit,
  aliases: string[],
  extra: Extra = {},
): FoodDef {
  const [kcal, proteinG, carbsG, fatG] = macros;
  const { alcoholG, source = 'curated', ...rest } = extra;
  return {
    id,
    name,
    emoji,
    category,
    diet,
    per100g: alcoholG
      ? { kcal, proteinG, carbsG, fatG, alcoholG }
      : { kcal, proteinG, carbsG, fatG },
    units,
    defaultUnit,
    aliases,
    source,
    ...rest,
  };
}

const G: Allergen[] = ['gluten'];
const D: Allergen[] = ['dairy'];
const GD: Allergen[] = ['gluten', 'dairy'];

export const FOODS: FoodDef[] = [
  // ── Breads ────────────────────────────────────────────────────────────────
  food(
    'roti',
    'Roti (chapati)',
    '🫓',
    'bread',
    'vegan',
    [264, 8.5, 49, 4],
    { piece: 40 },
    'piece',
    [
      'roti',
      'chapati',
      'chapathi',
      'chapatti',
      'phulka',
      'fulka',
      'rotli',
      'wheat roti',
      'atta roti',
      'tawa roti',
      'plain roti',
    ],
    { allergens: G },
  ),
  food(
    'ghee_roti',
    'Roti with ghee',
    '🫓',
    'bread',
    'veg',
    [297, 8.2, 47, 8.5],
    { piece: 42 },
    'piece',
    ['ghee roti', 'roti with ghee', 'chapati with ghee', 'butter roti', 'butter chapati'],
    { allergens: GD },
  ),
  food(
    'paratha',
    'Plain paratha',
    '🫓',
    'bread',
    'veg',
    [327, 7.5, 45, 13],
    { piece: 80 },
    'piece',
    ['paratha', 'parantha', 'plain paratha', 'lachha paratha', 'laccha paratha', 'tawa paratha'],
    { allergens: G, oilSensitive: true },
  ),
  food(
    'aloo_paratha',
    'Aloo paratha',
    '🫓',
    'bread',
    'veg',
    [252, 5.5, 35, 10],
    { piece: 130 },
    'piece',
    ['aloo paratha', 'aloo parantha', 'alu paratha', 'potato paratha'],
    { allergens: G, oilSensitive: true, jainAvoid: true },
  ),
  food(
    'paneer_paratha',
    'Paneer paratha',
    '🫓',
    'bread',
    'veg',
    [280, 10, 32, 12.5],
    { piece: 130 },
    'piece',
    ['paneer paratha', 'paneer parantha'],
    { allergens: GD, oilSensitive: true },
  ),
  food(
    'thepla',
    'Methi thepla',
    '🫓',
    'bread',
    'vegan',
    [310, 8.5, 42, 12],
    { piece: 40 },
    'piece',
    ['thepla', 'methi thepla'],
    { allergens: G },
  ),
  food(
    'puri',
    'Puri',
    '🫓',
    'bread',
    'vegan',
    [347, 6.5, 42, 17],
    { piece: 25 },
    'piece',
    ['puri', 'poori'],
    { allergens: G, oilSensitive: true },
  ),
  food(
    'bhatura',
    'Bhatura',
    '🫓',
    'bread',
    'veg',
    [330, 7, 45, 13.5],
    { piece: 70 },
    'piece',
    ['bhatura', 'bhature', 'bhatoora'],
    { allergens: GD, oilSensitive: true },
  ),
  food(
    'naan',
    'Naan',
    '🫓',
    'bread',
    'veg',
    [287, 9, 50, 5.7],
    { piece: 90 },
    'piece',
    ['naan', 'nan', 'butter naan', 'plain naan', 'tandoori naan', 'garlic naan', 'kulcha'],
    { allergens: GD },
  ),
  food(
    'tandoori_roti',
    'Tandoori roti',
    '🫓',
    'bread',
    'vegan',
    [271, 9, 52, 3],
    { piece: 60 },
    'piece',
    ['tandoori roti', 'tandoor roti'],
    { allergens: G },
  ),
  food(
    'bajra_roti',
    'Bajra roti',
    '🫓',
    'bread',
    'vegan',
    [280, 7.5, 50, 5.5],
    { piece: 50 },
    'piece',
    ['bajra roti', 'bajra rotla', 'bajre ki roti', 'millet roti'],
  ),
  food(
    'jowar_roti',
    'Jowar roti / bhakri',
    '🫓',
    'bread',
    'vegan',
    [270, 7.5, 52, 3.5],
    { piece: 50 },
    'piece',
    ['jowar roti', 'jowar bhakri', 'bhakri', 'jolada rotti'],
  ),
  food(
    'pav',
    'Pav',
    '🍞',
    'bread',
    'veg',
    [280, 9, 52, 4],
    { piece: 30 },
    'piece',
    ['pav', 'pao', 'ladi pav', 'bun', 'dinner roll'],
    { allergens: G },
  ),
  food(
    'bread_white',
    'White bread',
    '🍞',
    'bread',
    'veg',
    [265, 9, 49, 3.2],
    { slice: 25, piece: 25 },
    'slice',
    ['bread', 'white bread', 'sandwich bread', 'toast', 'bread toast', 'bread slice'],
    { allergens: G, source: 'usda' },
  ),
  food(
    'bread_brown',
    'Brown bread',
    '🍞',
    'bread',
    'vegan',
    [247, 13, 41, 3.4],
    { slice: 28, piece: 28 },
    'slice',
    ['brown bread', 'whole wheat bread', 'wheat bread', 'multigrain bread', 'atta bread'],
    { allergens: G, source: 'usda' },
  ),

  // ── Rice & grains ────────────────────────────────────────────────────────
  food(
    'white_rice',
    'Steamed rice',
    '🍚',
    'rice',
    'vegan',
    [130, 2.7, 28.2, 0.3],
    { bowl: 150, katori: 150, cup: 158, plate: 250, serving: 150 },
    'bowl',
    ['rice', 'chawal', 'plain rice', 'white rice', 'boiled rice', 'steamed rice', 'cooked rice'],
    { source: 'usda' },
  ),
  food(
    'brown_rice',
    'Brown rice',
    '🍚',
    'rice',
    'vegan',
    [123, 2.7, 25.6, 1],
    { bowl: 150, katori: 150, cup: 195, plate: 250 },
    'bowl',
    ['brown rice'],
    { source: 'usda' },
  ),
  food(
    'jeera_rice',
    'Jeera rice',
    '🍚',
    'rice',
    'veg',
    [151, 2.8, 26, 4],
    { bowl: 150, katori: 150, plate: 250 },
    'bowl',
    ['jeera rice', 'cumin rice'],
    { oilSensitive: true },
  ),
  food(
    'veg_pulao',
    'Veg pulao',
    '🍚',
    'rice',
    'veg',
    [151, 3.5, 23, 5],
    { bowl: 150, plate: 250 },
    'bowl',
    ['pulao', 'pulav', 'veg pulao', 'vegetable pulao', 'matar pulao'],
    { oilSensitive: true },
  ),
  food(
    'veg_biryani',
    'Veg biryani',
    '🍛',
    'rice',
    'veg',
    [155, 3.5, 23, 5.5],
    { bowl: 150, plate: 300 },
    'plate',
    ['veg biryani', 'vegetable biryani', 'paneer biryani'],
    { oilSensitive: true },
  ),
  food(
    'chicken_biryani',
    'Chicken biryani',
    '🍛',
    'rice',
    'nonveg',
    [170, 8, 20, 6.5],
    { bowl: 150, plate: 300 },
    'plate',
    ['biryani', 'chicken biryani', 'biriyani', 'chicken biriyani', 'dum biryani'],
    { oilSensitive: true },
  ),
  food(
    'mutton_biryani',
    'Mutton biryani',
    '🍛',
    'rice',
    'nonveg',
    [193, 9, 19, 9],
    { bowl: 150, plate: 300 },
    'plate',
    ['mutton biryani', 'lamb biryani', 'gosht biryani'],
    { oilSensitive: true },
  ),
  food(
    'khichdi',
    'Khichdi',
    '🍲',
    'rice',
    'veg',
    [121, 4.5, 19, 3],
    { bowl: 200, plate: 300, katori: 150 },
    'bowl',
    ['khichdi', 'khichri', 'dal khichdi', 'moong dal khichdi'],
  ),
  food(
    'curd_rice',
    'Curd rice',
    '🍚',
    'rice',
    'veg',
    [110, 3, 17, 3.3],
    { bowl: 200, plate: 250 },
    'bowl',
    ['curd rice', 'dahi rice', 'thayir sadam', 'dahi chawal'],
    { allergens: D },
  ),
  food(
    'lemon_rice',
    'Lemon rice',
    '🍚',
    'rice',
    'vegan',
    [160, 3, 27, 4.5],
    { bowl: 150, plate: 250 },
    'bowl',
    ['lemon rice', 'chitranna', 'pulihora', 'tamarind rice'],
    { oilSensitive: true },
  ),
  food(
    'fried_rice',
    'Veg fried rice',
    '🍚',
    'rice',
    'vegan',
    [163, 3.5, 25, 5.5],
    { bowl: 150, plate: 250 },
    'plate',
    ['fried rice', 'veg fried rice', 'schezwan fried rice'],
    { allergens: ['soy'], oilSensitive: true },
  ),

  // ── Breakfast ────────────────────────────────────────────────────────────
  food(
    'poha',
    'Poha',
    '🍛',
    'breakfast',
    'vegan',
    [161, 3, 26, 5],
    { plate: 150, bowl: 150 },
    'plate',
    ['poha', 'pohe', 'kanda poha', 'aval', 'chivda poha'],
    { oilSensitive: true, jainAvoid: true },
  ),
  food(
    'upma',
    'Upma',
    '🍛',
    'breakfast',
    'veg',
    [144, 3.5, 20, 5.5],
    { bowl: 150, plate: 200 },
    'bowl',
    ['upma', 'uppittu', 'rava upma', 'sooji upma'],
    { allergens: G, oilSensitive: true },
  ),
  food('idli', 'Idli', '🍘', 'breakfast', 'vegan', [131, 4.5, 27, 0.6], { piece: 40 }, 'piece', [
    'idli',
    'idly',
    'rava idli',
  ]),
  food(
    'dosa',
    'Plain dosa',
    '🥞',
    'breakfast',
    'vegan',
    [165, 4, 27, 4.5],
    { piece: 80 },
    'piece',
    ['dosa', 'plain dosa', 'dosai', 'sada dosa', 'neer dosa'],
    { oilSensitive: true },
  ),
  food(
    'masala_dosa',
    'Masala dosa',
    '🥞',
    'breakfast',
    'vegan',
    [179, 4, 26, 6.5],
    { piece: 180 },
    'piece',
    ['masala dosa', 'masala dosai', 'mysore masala dosa'],
    { oilSensitive: true, jainAvoid: true },
  ),
  food(
    'uttapam',
    'Uttapam',
    '🥞',
    'breakfast',
    'vegan',
    [148, 4, 24, 4],
    { piece: 120 },
    'piece',
    ['uttapam', 'uthappam', 'uttapa'],
    { oilSensitive: true },
  ),
  food(
    'medu_vada',
    'Medu vada',
    '🍩',
    'breakfast',
    'vegan',
    [300, 9, 30, 16],
    { piece: 50 },
    'piece',
    ['vada', 'medu vada', 'urad vada', 'vadai', 'uddina vada'],
    { oilSensitive: true },
  ),
  food(
    'sambar',
    'Sambar',
    '🍲',
    'dal',
    'vegan',
    [60, 3, 8, 1.8],
    { bowl: 150, katori: 150, cup: 200 },
    'bowl',
    ['sambar', 'sambhar'],
  ),
  food(
    'rasam',
    'Rasam',
    '🍲',
    'dal',
    'vegan',
    [35, 1.5, 5, 1],
    { bowl: 150, katori: 150, cup: 200 },
    'bowl',
    ['rasam', 'saaru'],
  ),
  food(
    'coconut_chutney',
    'Coconut chutney',
    '🥥',
    'breakfast',
    'vegan',
    [204, 2.5, 8, 18],
    { tbsp: 15, serving: 30, katori: 60 },
    'serving',
    ['chutney', 'coconut chutney', 'nariyal chutney', 'green chutney'],
  ),
  food(
    'oats',
    'Oats (dry)',
    '🥣',
    'breakfast',
    'vegan',
    [389, 16.9, 66.3, 6.9],
    { cup: 80, tbsp: 10, serving: 40 },
    'serving',
    ['oats', 'rolled oats', 'quaker oats', 'oat flakes', 'dry oats'],
    { allergens: G, source: 'usda' },
  ),
  food(
    'oats_porridge',
    'Oats porridge (with milk)',
    '🥣',
    'breakfast',
    'veg',
    [110, 4.5, 15, 3.5],
    { bowl: 200 },
    'bowl',
    ['oatmeal', 'porridge', 'oats porridge', 'oats with milk', 'overnight oats', 'masala oats'],
    { allergens: GD },
  ),
  food(
    'cornflakes',
    'Cornflakes',
    '🥣',
    'breakfast',
    'vegan',
    [357, 7.5, 84, 0.4],
    { bowl: 30, cup: 30, serving: 30 },
    'bowl',
    ['cornflakes', 'corn flakes', 'cereal', 'chocos'],
    { source: 'usda' },
  ),
  food(
    'muesli',
    'Muesli / granola',
    '🥣',
    'breakfast',
    'vegan',
    [370, 10, 66, 6],
    { bowl: 45, serving: 45, cup: 85 },
    'bowl',
    ['muesli', 'granola'],
    { allergens: ['nuts', 'gluten'] },
  ),
  food(
    'dhokla',
    'Dhokla',
    '🟨',
    'snack',
    'vegan',
    [160, 6, 25, 4],
    { piece: 30, plate: 150 },
    'piece',
    ['dhokla', 'khaman', 'khaman dhokla', 'khandvi'],
  ),

  // ── Dals & legumes ───────────────────────────────────────────────────────
  food(
    'dal',
    'Dal (tadka)',
    '🍲',
    'dal',
    'vegan',
    [110, 5.5, 14, 3.5],
    { bowl: 150, katori: 150, cup: 200, serving: 150 },
    'katori',
    [
      'dal',
      'daal',
      'dhal',
      'dal tadka',
      'dal fry',
      'toor dal',
      'arhar dal',
      'yellow dal',
      'moong dal',
      'masoor dal',
      'chana dal',
      'lentils',
      'lentil curry',
      'lentil soup',
      'varan',
      'pappu',
    ],
    { oilSensitive: true },
  ),
  food(
    'dal_makhani',
    'Dal makhani',
    '🍲',
    'dal',
    'veg',
    [150, 5.5, 14, 8],
    { bowl: 150, katori: 150 },
    'katori',
    ['dal makhani', 'maa ki dal', 'kaali dal', 'black dal'],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'rajma',
    'Rajma',
    '🫘',
    'dal',
    'vegan',
    [122, 5.5, 15, 4.5],
    { bowl: 150, katori: 150 },
    'katori',
    ['rajma', 'rajmah', 'rajma masala', 'kidney beans curry', 'kidney beans'],
    { oilSensitive: true },
  ),
  food(
    'chole',
    'Chole (chana masala)',
    '🫘',
    'dal',
    'vegan',
    [152, 6.5, 18, 6],
    { bowl: 150, katori: 150, plate: 200 },
    'katori',
    ['chole', 'chhole', 'chana masala', 'chickpea curry', 'chana curry', 'pindi chole', 'chana'],
    { oilSensitive: true },
  ),
  food(
    'sprouts',
    'Sprouts (moong)',
    '🌱',
    'dal',
    'vegan',
    [110, 7, 16, 2],
    { bowl: 100, katori: 100, cup: 100 },
    'bowl',
    [
      'sprouts',
      'moong sprouts',
      'sprouted moong',
      'sprout salad',
      'sprouts chaat',
      'usal',
      'matki',
    ],
    { jainAvoid: true },
  ),
  food(
    'chickpeas_boiled',
    'Chickpeas (boiled)',
    '🫘',
    'dal',
    'vegan',
    [164, 8.9, 27.4, 2.6],
    { cup: 164, bowl: 150, katori: 150 },
    'bowl',
    [
      'chickpeas',
      'boiled chickpeas',
      'kabuli chana',
      'boiled chana',
      'chana chaat',
      'chickpea salad',
    ],
    { source: 'usda' },
  ),
  food(
    'roasted_chana',
    'Roasted chana',
    '🫘',
    'snack',
    'vegan',
    [361, 20, 58, 5.5],
    { handful: 30, serving: 30, cup: 100 },
    'handful',
    ['roasted chana', 'bhuna chana', 'roasted gram', 'bhuna channa', 'chana jor garam'],
  ),
  food(
    'soy_chunks',
    'Soya chunks (dry)',
    '🟤',
    'dal',
    'vegan',
    [344.5, 52, 33, 0.5],
    { serving: 30, handful: 25, cup: 50 },
    'serving',
    ['soya chunks', 'soy chunks', 'nutrela', 'soya bari', 'meal maker', 'soya granules'],
    { allergens: ['soy'] },
  ),
  food(
    'soya_curry',
    'Soya chunk curry',
    '🍛',
    'curry',
    'vegan',
    [133, 12, 10, 5],
    { bowl: 150, katori: 150 },
    'bowl',
    ['soya curry', 'soya chunks curry', 'soya sabzi', 'soya masala', 'soya chunk curry'],
    { allergens: ['soy'], oilSensitive: true },
  ),
  food(
    'kadhi',
    'Kadhi',
    '🍲',
    'dal',
    'veg',
    [90, 3, 7, 5.5],
    { bowl: 150, katori: 150 },
    'katori',
    ['kadhi', 'kadi', 'kadhi pakora', 'kadhi chawal'],
    { allergens: D, oilSensitive: true },
  ),

  // ── Veg curries & sabzi ──────────────────────────────────────────────────
  food(
    'aloo_sabzi',
    'Aloo sabzi',
    '🥔',
    'veg',
    'vegan',
    [121, 2, 16, 5.5],
    { bowl: 150, katori: 150 },
    'katori',
    [
      'aloo sabzi',
      'aloo sabji',
      'aloo ki sabzi',
      'potato sabzi',
      'aloo bhaji',
      'aloo curry',
      'batata bhaji',
      'jeera aloo',
      'dum aloo',
      'potato curry',
    ],
    { oilSensitive: true, jainAvoid: true },
  ),
  food(
    'aloo_gobi',
    'Aloo gobi',
    '🥦',
    'veg',
    'vegan',
    [99, 2.5, 11, 5],
    { bowl: 150, katori: 150 },
    'katori',
    ['aloo gobi', 'gobi aloo', 'aloo gobhi'],
    { oilSensitive: true, jainAvoid: true },
  ),
  food(
    'gobi_sabzi',
    'Gobi sabzi',
    '🥦',
    'veg',
    'vegan',
    [91.5, 2.5, 8, 5.5],
    { bowl: 150, katori: 150 },
    'katori',
    ['gobi sabzi', 'cauliflower sabzi', 'gobhi', 'phool gobi', 'cauliflower curry'],
    { oilSensitive: true },
  ),
  food(
    'bhindi',
    'Bhindi sabzi',
    '🫑',
    'veg',
    'vegan',
    [100, 2.5, 9, 6],
    { bowl: 150, katori: 150 },
    'katori',
    ['bhindi', 'bhindi sabzi', 'okra', 'bhindi masala', 'bhindi fry', 'ladyfinger', 'bhendi'],
    { oilSensitive: true },
  ),
  food(
    'mixed_veg',
    'Mixed veg sabzi',
    '🥘',
    'veg',
    'vegan',
    [91, 2.5, 9, 5],
    { bowl: 150, katori: 150, serving: 150 },
    'katori',
    [
      'sabzi',
      'sabji',
      'subzi',
      'mixed veg',
      'mix veg',
      'mixed vegetable',
      'vegetable curry',
      'veg curry',
      'tarkari',
      'bhaji',
      'shaak',
      'poriyal',
      'thoran',
      'vegetables',
    ],
    { oilSensitive: true },
  ),
  food(
    'baingan_bharta',
    'Baingan bharta',
    '🍆',
    'veg',
    'vegan',
    [85, 2, 8, 5],
    { bowl: 150, katori: 150 },
    'katori',
    ['baingan bharta', 'baingan', 'brinjal', 'eggplant', 'brinjal curry', 'vangi'],
    { oilSensitive: true },
  ),
  food(
    'palak_sabzi',
    'Palak sabzi',
    '🥬',
    'veg',
    'vegan',
    [81.5, 3, 5, 5.5],
    { bowl: 150, katori: 150 },
    'katori',
    ['palak', 'palak sabzi', 'spinach sabzi', 'saag', 'sarson ka saag', 'spinach curry'],
    { oilSensitive: true },
  ),
  food(
    'lauki_sabzi',
    'Lauki / tori sabzi',
    '🥒',
    'veg',
    'vegan',
    [61.5, 1.5, 6, 3.5],
    { bowl: 150, katori: 150 },
    'katori',
    ['lauki', 'lauki sabzi', 'dudhi', 'bottle gourd', 'ghiya', 'tori', 'turai', 'tinda'],
    { oilSensitive: true },
  ),
  food(
    'cabbage_sabzi',
    'Cabbage sabzi',
    '🥬',
    'veg',
    'vegan',
    [76.5, 2, 7, 4.5],
    { bowl: 150, katori: 150 },
    'katori',
    ['cabbage', 'cabbage sabzi', 'patta gobi', 'band gobhi'],
    { oilSensitive: true },
  ),
  food(
    'paneer_sabzi',
    'Paneer sabzi',
    '🧀',
    'curry',
    'veg',
    [172, 8, 8, 12],
    { bowl: 150, katori: 150, serving: 150 },
    'katori',
    [
      'paneer sabzi',
      'paneer sabji',
      'paneer curry',
      'paneer masala',
      'kadai paneer',
      'paneer ki sabzi',
      'paneer gravy',
    ],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'matar_paneer',
    'Matar paneer',
    '🧀',
    'curry',
    'veg',
    [160.5, 7.5, 9, 10.5],
    { bowl: 150, katori: 150 },
    'katori',
    ['matar paneer', 'mutter paneer', 'peas paneer'],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'palak_paneer',
    'Palak paneer',
    '🧀',
    'curry',
    'veg',
    [151, 7, 6, 11],
    { bowl: 150, katori: 150 },
    'katori',
    ['palak paneer', 'saag paneer'],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'paneer_butter_masala',
    'Paneer butter masala',
    '🧀',
    'curry',
    'veg',
    [235, 8, 8, 19],
    { bowl: 150, katori: 150 },
    'bowl',
    [
      'paneer butter masala',
      'butter paneer',
      'shahi paneer',
      'paneer makhani',
      'paneer tikka masala',
    ],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'paneer_bhurji',
    'Paneer bhurji',
    '🧀',
    'curry',
    'veg',
    [234, 13, 5, 18],
    { serving: 120, bowl: 150, katori: 120 },
    'serving',
    ['paneer bhurji', 'scrambled paneer'],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'paneer_tikka',
    'Paneer tikka',
    '🧀',
    'curry',
    'veg',
    [250.5, 15, 6, 18.5],
    { piece: 30, serving: 150, plate: 200 },
    'serving',
    ['paneer tikka', 'tandoori paneer'],
    { allergens: D },
  ),
  food(
    'malai_kofta',
    'Malai kofta',
    '🍛',
    'curry',
    'veg',
    [221, 5, 12, 17],
    { bowl: 150, katori: 150 },
    'bowl',
    ['malai kofta', 'kofta curry', 'kofta'],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'pav_bhaji',
    'Pav bhaji',
    '🍛',
    'fast_food',
    'veg',
    [171, 4, 23, 7],
    { plate: 300, serving: 300 },
    'plate',
    ['pav bhaji'],
    { allergens: GD, oilSensitive: true, jainAvoid: true },
  ),
  food(
    'raita',
    'Raita',
    '🥣',
    'dairy',
    'veg',
    [68, 3, 5, 4],
    { bowl: 100, katori: 100 },
    'katori',
    ['raita', 'boondi raita', 'cucumber raita', 'pachadi'],
    { allergens: D },
  ),
  food(
    'salad',
    'Green salad',
    '🥗',
    'raw_veg',
    'vegan',
    [20.6, 1.2, 3.5, 0.2],
    { bowl: 100, plate: 150, serving: 100 },
    'bowl',
    ['salad', 'green salad', 'kachumber', 'cucumber salad', 'garden salad', 'veg salad'],
  ),

  // ── Non-veg ──────────────────────────────────────────────────────────────
  food(
    'chicken_curry',
    'Chicken curry',
    '🍗',
    'nonveg',
    'nonveg',
    [140, 13, 4, 8],
    { bowl: 150, katori: 150, serving: 150 },
    'bowl',
    [
      'chicken curry',
      'chicken gravy',
      'chicken masala',
      'kadai chicken',
      'chicken korma',
      'home style chicken',
    ],
    { oilSensitive: true },
  ),
  food(
    'butter_chicken',
    'Butter chicken',
    '🍗',
    'nonveg',
    'nonveg',
    [188.5, 13, 6, 12.5],
    { bowl: 150, katori: 150 },
    'bowl',
    ['butter chicken', 'murgh makhani', 'chicken tikka masala', 'chicken makhani'],
    { allergens: D, oilSensitive: true },
  ),
  food(
    'chicken_breast',
    'Grilled chicken breast',
    '🍗',
    'nonveg',
    'nonveg',
    [165, 31, 0, 3.6],
    { piece: 120, serving: 100 },
    'serving',
    [
      'chicken breast',
      'grilled chicken',
      'boiled chicken',
      'chicken',
      'roast chicken',
      'baked chicken',
    ],
    { source: 'usda' },
  ),
  food(
    'tandoori_chicken',
    'Tandoori chicken / tikka',
    '🍗',
    'nonveg',
    'nonveg',
    [150, 21, 3, 6],
    { piece: 80, serving: 150, plate: 250 },
    'serving',
    [
      'tandoori chicken',
      'chicken tikka',
      'chicken tandoori',
      'tangdi kabab',
      'chicken kebab',
      'chicken kabab',
    ],
    { allergens: D },
  ),
  food(
    'chicken_momos',
    'Chicken momos',
    '🥟',
    'nonveg',
    'nonveg',
    [149, 8, 18, 5],
    { piece: 30, plate: 240 },
    'piece',
    ['chicken momos', 'chicken momo', 'chicken dumplings'],
    { allergens: G },
  ),
  food(
    'egg_curry',
    'Egg curry',
    '🥚',
    'nonveg',
    'egg',
    [151, 8, 5, 11],
    { bowl: 150, katori: 150 },
    'bowl',
    ['egg curry', 'anda curry', 'egg masala'],
    { allergens: ['egg'], oilSensitive: true },
  ),
  food(
    'fish_curry',
    'Fish curry',
    '🐟',
    'nonveg',
    'nonveg',
    [122, 13, 4, 6],
    { bowl: 150, katori: 150 },
    'bowl',
    ['fish curry', 'macher jhol', 'fish gravy', 'meen curry'],
    { allergens: ['fish'], oilSensitive: true },
  ),
  food(
    'fish_fry',
    'Fish fry',
    '🐟',
    'nonveg',
    'nonveg',
    [229.5, 18, 9, 13.5],
    { piece: 80, serving: 120 },
    'piece',
    ['fish fry', 'fried fish', 'rava fish fry', 'fish tikka'],
    { allergens: ['fish'], oilSensitive: true },
  ),
  food(
    'grilled_fish',
    'Grilled fish',
    '🐟',
    'nonveg',
    'nonveg',
    [128, 26, 0, 2.6],
    { piece: 120, serving: 120 },
    'serving',
    ['grilled fish', 'baked fish', 'steamed fish', 'fish'],
    { allergens: ['fish'], source: 'usda' },
  ),
  food(
    'mutton_curry',
    'Mutton curry',
    '🍖',
    'nonveg',
    'nonveg',
    [202, 15, 4, 14],
    { bowl: 150, katori: 150 },
    'bowl',
    ['mutton curry', 'mutton', 'lamb curry', 'goat curry', 'rogan josh', 'mutton gravy'],
    { oilSensitive: true },
  ),
  food(
    'keema',
    'Keema',
    '🍖',
    'nonveg',
    'nonveg',
    [233, 15, 5, 17],
    { bowl: 150, katori: 150 },
    'bowl',
    ['keema', 'kheema', 'mince curry', 'keema matar', 'chicken keema'],
    { oilSensitive: true },
  ),
  food(
    'prawn_curry',
    'Prawn curry',
    '🦐',
    'nonveg',
    'nonveg',
    [130.5, 14, 4, 6.5],
    { bowl: 150, katori: 150 },
    'bowl',
    ['prawn curry', 'prawns', 'shrimp curry', 'jhinga', 'prawn masala'],
    { allergens: ['shellfish'], oilSensitive: true },
  ),

  // ── Eggs ─────────────────────────────────────────────────────────────────
  food(
    'boiled_egg',
    'Egg (boiled)',
    '🥚',
    'egg',
    'egg',
    [155, 12.6, 1.1, 10.6],
    { piece: 50 },
    'piece',
    ['egg', 'boiled egg', 'anda', 'hard boiled egg', 'whole egg', 'egg boiled'],
    { allergens: ['egg'], source: 'usda' },
  ),
  food(
    'omelette',
    'Omelette',
    '🍳',
    'egg',
    'egg',
    [154, 10.6, 0.6, 11.7],
    { piece: 120, serving: 120 },
    'piece',
    ['omelette', 'omelet', 'masala omelette', 'egg omelette', 'cheese omelette'],
    { allergens: ['egg'], oilSensitive: true, source: 'usda' },
  ),
  food(
    'fried_egg',
    'Fried egg',
    '🍳',
    'egg',
    'egg',
    [196, 13.6, 0.8, 14.8],
    { piece: 46 },
    'piece',
    ['fried egg', 'egg fry', 'half fry', 'sunny side up', 'bullseye', 'bull eye'],
    { allergens: ['egg'], oilSensitive: true, source: 'usda' },
  ),
  food(
    'egg_white',
    'Egg white',
    '🥚',
    'egg',
    'egg',
    [52, 10.9, 0.7, 0.2],
    { piece: 33 },
    'piece',
    ['egg white', 'boiled egg white'],
    { allergens: ['egg'], source: 'usda' },
  ),
  food(
    'scrambled_eggs',
    'Scrambled eggs / bhurji',
    '🍳',
    'egg',
    'egg',
    [149, 10, 1.6, 11],
    { serving: 120, plate: 150 },
    'serving',
    ['scrambled eggs', 'scrambled egg', 'egg bhurji', 'anda bhurji'],
    { allergens: ['egg'], oilSensitive: true },
  ),

  // ── Dairy ────────────────────────────────────────────────────────────────
  food(
    'milk_toned',
    'Milk (toned)',
    '🥛',
    'dairy',
    'veg',
    [58, 3.1, 4.7, 3],
    { glass: 250, cup: 200 },
    'glass',
    [
      'milk',
      'doodh',
      'toned milk',
      'cow milk',
      'plain milk',
      'warm milk',
      'haldi milk',
      'turmeric milk',
    ],
    { allergens: D, liquid: true },
  ),
  food(
    'milk_full',
    'Milk (full cream)',
    '🥛',
    'dairy',
    'veg',
    [86, 3.2, 4.8, 6],
    { glass: 250, cup: 200 },
    'glass',
    ['full cream milk', 'whole milk', 'buffalo milk', 'full fat milk'],
    { allergens: D, liquid: true },
  ),
  food(
    'milk_skim',
    'Milk (double toned / skim)',
    '🥛',
    'dairy',
    'veg',
    [46, 3.3, 4.8, 1.5],
    { glass: 250, cup: 200 },
    'glass',
    ['skimmed milk', 'skim milk', 'double toned milk', 'low fat milk'],
    { allergens: D, liquid: true },
  ),
  food(
    'curd',
    'Curd (dahi)',
    '🥣',
    'dairy',
    'veg',
    [61, 3.5, 4.7, 3.3],
    { bowl: 150, katori: 150, cup: 245 },
    'katori',
    ['curd', 'dahi', 'yogurt', 'yoghurt', 'plain yogurt', 'doi', 'mosaru'],
    { allergens: D, source: 'usda' },
  ),
  food(
    'greek_yogurt',
    'Greek yogurt / hung curd',
    '🥣',
    'dairy',
    'veg',
    [59, 10.2, 3.6, 0.4],
    { cup: 170, bowl: 150, serving: 150 },
    'serving',
    ['greek yogurt', 'hung curd', 'skyr', 'high protein yogurt', 'protein yogurt'],
    { allergens: D, source: 'usda' },
  ),
  food(
    'paneer',
    'Paneer (raw)',
    '🧀',
    'dairy',
    'veg',
    [291, 18, 3, 23],
    { piece: 20, slice: 30, serving: 100 },
    'serving',
    ['paneer', 'cottage cheese', 'raw paneer', 'paneer cubes'],
    { allergens: D },
  ),
  food(
    'cheese_slice',
    'Cheese slice',
    '🧀',
    'dairy',
    'veg',
    [317, 20, 3, 25],
    { slice: 20, piece: 20 },
    'slice',
    ['cheese slice', 'cheese', 'processed cheese', 'amul cheese', 'cheese cube'],
    { allergens: D },
  ),
  food(
    'mozzarella',
    'Mozzarella',
    '🧀',
    'dairy',
    'veg',
    [280, 27.5, 3.1, 17.1],
    { slice: 20, serving: 30 },
    'serving',
    ['mozzarella', 'pizza cheese'],
    { allergens: D, source: 'usda' },
  ),
  food(
    'buttermilk',
    'Buttermilk (chaas)',
    '🥛',
    'beverage',
    'veg',
    [25, 1.5, 2.5, 1],
    { glass: 250, cup: 200 },
    'glass',
    ['buttermilk', 'chaas', 'chaach', 'mattha', 'majjige', 'taak', 'masala chaas'],
    { allergens: D, liquid: true },
  ),
  food(
    'lassi',
    'Sweet lassi',
    '🥛',
    'beverage',
    'veg',
    [99, 3, 15, 3],
    { glass: 250, cup: 200 },
    'glass',
    ['lassi', 'sweet lassi', 'mango lassi', 'salted lassi'],
    { allergens: D, liquid: true },
  ),
  food(
    'butter',
    'Butter',
    '🧈',
    'fat',
    'veg',
    [717, 0.9, 0.1, 81],
    { tsp: 5, tbsp: 14 },
    'tsp',
    ['butter', 'makhan', 'amul butter', 'white butter'],
    { allergens: D, source: 'usda' },
  ),
  food(
    'ghee',
    'Ghee',
    '🧈',
    'fat',
    'veg',
    [898, 0, 0, 99.8],
    { tsp: 5, tbsp: 13 },
    'tsp',
    ['ghee', 'clarified butter', 'desi ghee'],
    { allergens: D },
  ),
  food(
    'oil',
    'Cooking oil',
    '🫗',
    'fat',
    'vegan',
    [884, 0, 0, 100],
    { tsp: 4.5, tbsp: 13.5 },
    'tsp',
    [
      'oil',
      'cooking oil',
      'olive oil',
      'vegetable oil',
      'mustard oil',
      'refined oil',
      'coconut oil',
      'groundnut oil',
    ],
    { source: 'usda' },
  ),
  food(
    'whey',
    'Whey protein',
    '💪',
    'supplement',
    'veg',
    [397, 80, 8, 5],
    { scoop: 30, serving: 30 },
    'scoop',
    ['whey', 'whey protein', 'protein powder', 'scoop of whey', 'protein scoop', 'whey isolate'],
    { allergens: D },
  ),
  food(
    'protein_shake',
    'Protein shake (whey + milk)',
    '🥤',
    'supplement',
    'veg',
    [95, 11.4, 5.1, 3.2],
    { glass: 280, serving: 280, cup: 280 },
    'glass',
    ['protein shake', 'whey shake', 'shake with milk', 'protein smoothie', 'whey with milk'],
    { allergens: D, liquid: true },
  ),
  food(
    'ice_cream',
    'Ice cream',
    '🍨',
    'sweet',
    'veg',
    [207, 3.5, 23.6, 11],
    { scoop: 66, cup: 100, serving: 100 },
    'scoop',
    ['ice cream', 'icecream', 'gelato', 'sundae'],
    { allergens: D, source: 'usda' },
  ),
  food(
    'kulfi',
    'Kulfi',
    '🍦',
    'sweet',
    'veg',
    [241, 6, 25, 13],
    { piece: 70 },
    'piece',
    ['kulfi', 'matka kulfi'],
    { allergens: D },
  ),

  // ── Fruits ───────────────────────────────────────────────────────────────
  food(
    'banana',
    'Banana',
    '🍌',
    'fruit',
    'vegan',
    [89, 1.1, 22.8, 0.3],
    { piece: 118 },
    'piece',
    ['banana', 'kela', 'elaichi banana'],
    { source: 'usda' },
  ),
  food(
    'apple',
    'Apple',
    '🍎',
    'fruit',
    'vegan',
    [52, 0.3, 13.8, 0.2],
    { piece: 182, slice: 25 },
    'piece',
    ['apple', 'seb', 'green apple'],
    { source: 'usda' },
  ),
  food(
    'mango',
    'Mango',
    '🥭',
    'fruit',
    'vegan',
    [60, 0.8, 15, 0.4],
    { piece: 200, bowl: 150, cup: 165, slice: 50 },
    'piece',
    ['mango', 'aam', 'alphonso', 'hapus', 'mango slices'],
    { source: 'usda' },
  ),
  food(
    'orange',
    'Orange',
    '🍊',
    'fruit',
    'vegan',
    [47, 0.9, 11.8, 0.1],
    { piece: 130 },
    'piece',
    ['orange', 'santra', 'mosambi', 'sweet lime', 'kinnow', 'tangerine'],
    { source: 'usda' },
  ),
  food(
    'papaya',
    'Papaya',
    '🍈',
    'fruit',
    'vegan',
    [43, 0.5, 10.8, 0.3],
    { bowl: 150, cup: 145, slice: 100 },
    'bowl',
    ['papaya', 'papita'],
    { source: 'usda' },
  ),
  food(
    'watermelon',
    'Watermelon',
    '🍉',
    'fruit',
    'vegan',
    [30, 0.6, 7.6, 0.2],
    { bowl: 150, slice: 280, cup: 152 },
    'bowl',
    ['watermelon', 'tarbooj', 'tarbuj'],
    { source: 'usda' },
  ),
  food(
    'grapes',
    'Grapes',
    '🍇',
    'fruit',
    'vegan',
    [69, 0.7, 18.1, 0.2],
    { bowl: 150, cup: 151, handful: 50 },
    'bowl',
    ['grapes', 'angoor'],
    { source: 'usda' },
  ),
  food(
    'pomegranate',
    'Pomegranate',
    '🍎',
    'fruit',
    'vegan',
    [83, 1.7, 18.7, 1.2],
    { bowl: 150, cup: 174, piece: 175 },
    'bowl',
    ['pomegranate', 'anar', 'pomegranate seeds'],
    { source: 'usda' },
  ),
  food(
    'guava',
    'Guava',
    '🍐',
    'fruit',
    'vegan',
    [68, 2.6, 14.3, 1],
    { piece: 100 },
    'piece',
    ['guava', 'amrood', 'amrud', 'peru'],
    { source: 'usda' },
  ),
  food(
    'chikoo',
    'Chikoo',
    '🟤',
    'fruit',
    'vegan',
    [83, 0.4, 20, 1.1],
    { piece: 100 },
    'piece',
    ['chikoo', 'chiku', 'sapota', 'sapodilla'],
    { source: 'usda' },
  ),
  food(
    'pineapple',
    'Pineapple',
    '🍍',
    'fruit',
    'vegan',
    [50, 0.5, 13.1, 0.1],
    { bowl: 150, slice: 85, cup: 165 },
    'bowl',
    ['pineapple', 'ananas'],
    { source: 'usda' },
  ),
  food(
    'strawberries',
    'Strawberries',
    '🍓',
    'fruit',
    'vegan',
    [32, 0.7, 7.7, 0.3],
    { bowl: 150, cup: 150, piece: 12 },
    'bowl',
    ['strawberries', 'strawberry', 'berries'],
    { source: 'usda' },
  ),
  food(
    'fruit_bowl',
    'Fruit bowl',
    '🍱',
    'fruit',
    'vegan',
    [60, 0.8, 15, 0.3],
    { bowl: 150, plate: 200 },
    'bowl',
    [
      'fruit salad',
      'fruits',
      'mixed fruit',
      'fruit bowl',
      'fruit chaat',
      'fruit plate',
      'cut fruit',
    ],
  ),
  food(
    'dates',
    'Dates',
    '🌴',
    'fruit',
    'vegan',
    [282, 2.5, 75, 0.4],
    { piece: 8, handful: 40 },
    'piece',
    ['dates', 'date', 'khajur', 'khajoor', 'medjool dates'],
    { source: 'usda' },
  ),
  food(
    'raisins',
    'Raisins',
    '🍇',
    'fruit',
    'vegan',
    [299, 3.1, 79, 0.5],
    { tbsp: 9, handful: 30 },
    'tbsp',
    ['raisins', 'kishmish', 'kismis'],
    { source: 'usda' },
  ),

  // ── Nuts & seeds ─────────────────────────────────────────────────────────
  food(
    'almonds',
    'Almonds',
    '🌰',
    'nut',
    'vegan',
    [579, 21.2, 21.6, 49.9],
    { piece: 1.2, handful: 25 },
    'handful',
    ['almonds', 'almond', 'badam', 'soaked almonds'],
    { allergens: ['nuts'], source: 'usda' },
  ),
  food(
    'cashews',
    'Cashews',
    '🥜',
    'nut',
    'vegan',
    [553, 18.2, 30.2, 43.9],
    { piece: 1.6, handful: 25 },
    'handful',
    ['cashews', 'cashew', 'kaju'],
    { allergens: ['nuts'], source: 'usda' },
  ),
  food(
    'walnuts',
    'Walnuts',
    '🌰',
    'nut',
    'vegan',
    [654, 15.2, 13.7, 65.2],
    { piece: 4, handful: 25 },
    'handful',
    ['walnuts', 'walnut', 'akhrot'],
    { allergens: ['nuts'], source: 'usda' },
  ),
  food(
    'peanuts',
    'Peanuts',
    '🥜',
    'nut',
    'vegan',
    [585, 23.7, 21.5, 49.7],
    { handful: 30, tbsp: 9 },
    'handful',
    ['peanuts', 'peanut', 'groundnuts', 'moongfali', 'singdana', 'roasted peanuts'],
    { allergens: ['peanut'], source: 'usda' },
  ),
  food(
    'peanut_butter',
    'Peanut butter',
    '🥜',
    'nut',
    'vegan',
    [588, 25, 20, 50],
    { tbsp: 16, tsp: 5 },
    'tbsp',
    ['peanut butter', 'pb'],
    { allergens: ['peanut'], source: 'usda' },
  ),
  food(
    'makhana',
    'Makhana',
    '⚪',
    'snack',
    'vegan',
    [348, 9.7, 77, 0.1],
    { bowl: 30, handful: 15, cup: 15 },
    'bowl',
    ['makhana', 'fox nuts', 'lotus seeds', 'phool makhana', 'roasted makhana'],
  ),
  food(
    'chia_seeds',
    'Chia seeds',
    '🌱',
    'nut',
    'vegan',
    [486, 16.5, 42.1, 30.7],
    { tbsp: 12, tsp: 4 },
    'tbsp',
    ['chia seeds', 'chia'],
    { source: 'usda' },
  ),
  food(
    'flax_seeds',
    'Flax seeds',
    '🌱',
    'nut',
    'vegan',
    [534, 18.3, 28.9, 42.2],
    { tbsp: 10, tsp: 3.5 },
    'tbsp',
    ['flax seeds', 'flaxseed', 'alsi', 'linseed'],
    { source: 'usda' },
  ),

  // ── Snacks & fast food ───────────────────────────────────────────────────
  food(
    'samosa',
    'Samosa',
    '🥟',
    'snack',
    'veg',
    [284, 5, 30, 16],
    { piece: 90 },
    'piece',
    ['samosa', 'aloo samosa', 'punjabi samosa'],
    { allergens: G, oilSensitive: true, jainAvoid: true },
  ),
  food(
    'pakora',
    'Pakora',
    '🍤',
    'snack',
    'vegan',
    [299, 7, 25, 19],
    { piece: 20, plate: 150 },
    'piece',
    ['pakora', 'pakoda', 'bhajji', 'bhajiya', 'onion pakoda', 'kanda bhaji', 'pakode'],
    { oilSensitive: true, jainAvoid: true },
  ),
  food(
    'vada_pav',
    'Vada pav',
    '🍔',
    'snack',
    'veg',
    [271.5, 6, 36, 11.5],
    { piece: 110 },
    'piece',
    ['vada pav', 'wada pav', 'vadapav'],
    { allergens: G, oilSensitive: true, jainAvoid: true },
  ),
  food(
    'kachori',
    'Kachori',
    '🥟',
    'snack',
    'veg',
    [398, 8, 42, 22],
    { piece: 50 },
    'piece',
    ['kachori', 'khasta kachori', 'pyaz kachori'],
    { allergens: G, oilSensitive: true },
  ),
  food(
    'bhel_puri',
    'Bhel puri',
    '🥗',
    'snack',
    'vegan',
    [202, 5, 32, 6],
    { plate: 150, bowl: 150 },
    'plate',
    ['bhel', 'bhel puri', 'chaat', 'jhalmuri', 'sev puri', 'dahi puri', 'papdi chaat'],
    { jainAvoid: true },
  ),
  food(
    'pani_puri',
    'Pani puri',
    '🫧',
    'snack',
    'vegan',
    [180, 3.5, 28, 6],
    { piece: 20, plate: 120 },
    'piece',
    ['pani puri', 'golgappa', 'gol gappe', 'puchka', 'pani poori'],
    { allergens: G, jainAvoid: true },
  ),
  food(
    'namkeen',
    'Namkeen / bhujia',
    '🥨',
    'snack',
    'vegan',
    [561, 12, 45, 37],
    { handful: 30, bowl: 50, serving: 30 },
    'handful',
    ['namkeen', 'bhujia', 'sev', 'mixture', 'chivda', 'farsan', 'aloo bhujia', 'haldiram'],
  ),
  food(
    'chips',
    'Potato chips',
    '🥔',
    'snack',
    'vegan',
    [551.4, 7, 53, 34.6],
    { serving: 30, handful: 20 },
    'serving',
    ['chips', 'potato chips', 'wafers', 'lays', 'crisps'],
    { jainAvoid: true },
  ),
  food(
    'biscuits',
    'Biscuits',
    '🍪',
    'snack',
    'veg',
    [454, 7, 75, 14],
    { piece: 7 },
    'piece',
    [
      'biscuits',
      'biscuit',
      'marie',
      'marie biscuit',
      'parle g',
      'glucose biscuits',
      'digestive biscuits',
      'good day',
    ],
    { allergens: G },
  ),
  food(
    'cookies',
    'Cookies',
    '🍪',
    'snack',
    'veg',
    [492, 5, 64, 24],
    { piece: 15 },
    'piece',
    ['cookie', 'cookies', 'chocolate chip cookie', 'choco chip cookies', 'oreo'],
    { allergens: GD },
  ),
  food(
    'rusk',
    'Rusk',
    '🍞',
    'snack',
    'veg',
    [404, 11, 72, 8],
    { piece: 10 },
    'piece',
    ['rusk', 'toast rusk', 'cake rusk'],
    { allergens: G },
  ),
  food(
    'khakhra',
    'Khakhra',
    '🫓',
    'snack',
    'vegan',
    [374, 11, 60, 10],
    { piece: 15 },
    'piece',
    ['khakhra', 'khakra'],
    { allergens: G },
  ),
  food(
    'popcorn',
    'Popcorn',
    '🍿',
    'snack',
    'vegan',
    [387, 13, 78, 4.5],
    { bowl: 25, cup: 8 },
    'bowl',
    ['popcorn'],
    { source: 'usda' },
  ),
  food(
    'veg_momos',
    'Veg momos',
    '🥟',
    'fast_food',
    'vegan',
    [133, 4.5, 22, 3],
    { piece: 30, plate: 240 },
    'piece',
    ['momos', 'momo', 'veg momos', 'steamed momos', 'dumplings'],
    { allergens: G },
  ),
  food(
    'sandwich',
    'Veg sandwich',
    '🥪',
    'fast_food',
    'veg',
    [229, 7, 30, 9],
    { piece: 150 },
    'piece',
    [
      'sandwich',
      'veg sandwich',
      'grilled sandwich',
      'bombay sandwich',
      'cheese sandwich',
      'club sandwich',
    ],
    { allergens: GD },
  ),
  food(
    'burger',
    'Burger',
    '🍔',
    'fast_food',
    'veg',
    [250.5, 11, 28, 10.5],
    { piece: 180 },
    'piece',
    ['burger', 'veg burger', 'aloo tikki burger', 'mcaloo tikki', 'chicken burger', 'cheeseburger'],
    { allergens: GD },
  ),
  food(
    'pizza',
    'Pizza',
    '🍕',
    'fast_food',
    'veg',
    [266, 11.4, 33, 10],
    { slice: 107, piece: 107 },
    'slice',
    ['pizza', 'pizza slice', 'margherita', 'cheese pizza', 'veg pizza'],
    { allergens: GD, source: 'usda' },
  ),
  food(
    'french_fries',
    'French fries',
    '🍟',
    'fast_food',
    'vegan',
    [312, 3.4, 41, 15],
    { serving: 117, plate: 117, handful: 30 },
    'serving',
    ['french fries', 'fries', 'finger chips'],
    { oilSensitive: true, jainAvoid: true, source: 'usda' },
  ),
  food(
    'kathi_roll',
    'Kathi roll / frankie',
    '🌯',
    'fast_food',
    'veg',
    [238, 9, 28, 10],
    { piece: 180 },
    'piece',
    [
      'roll',
      'frankie',
      'kathi roll',
      'wrap',
      'paneer roll',
      'chicken roll',
      'egg roll',
      'shawarma',
    ],
    { allergens: G },
  ),
  food(
    'pasta_red',
    'Pasta in tomato sauce',
    '🍝',
    'fast_food',
    'vegan',
    [133, 4.5, 22, 3],
    { plate: 250, bowl: 200 },
    'plate',
    ['pasta', 'red sauce pasta', 'spaghetti', 'penne', 'arrabiata', 'macaroni'],
    { allergens: G },
  ),
  food(
    'pasta_white',
    'Pasta in white sauce',
    '🍝',
    'fast_food',
    'veg',
    [180.5, 6, 20, 8.5],
    { plate: 250, bowl: 200 },
    'plate',
    ['white sauce pasta', 'alfredo pasta', 'cheesy pasta', 'mac and cheese'],
    { allergens: GD },
  ),
  food(
    'hakka_noodles',
    'Hakka noodles',
    '🍜',
    'fast_food',
    'vegan',
    [170, 4, 25, 6],
    { plate: 250, bowl: 200 },
    'plate',
    ['noodles', 'chowmein', 'chow mein', 'hakka noodles', 'schezwan noodles'],
    { allergens: ['gluten', 'soy'], oilSensitive: true },
  ),
  food(
    'instant_noodles',
    'Instant noodles (1 pack)',
    '🍜',
    'fast_food',
    'veg',
    [137, 3, 18.5, 5.6],
    { serving: 230, bowl: 230, plate: 230 },
    'serving',
    ['maggi', 'instant noodles', 'ramen', 'top ramen', 'yippee', 'cup noodles'],
    { allergens: G, source: 'usda' },
  ),

  // ── Sweets ───────────────────────────────────────────────────────────────
  food(
    'gulab_jamun',
    'Gulab jamun',
    '🟤',
    'sweet',
    'veg',
    [321.5, 4.5, 50, 11.5],
    { piece: 50 },
    'piece',
    ['gulab jamun', 'gulabjamun', 'kala jamun'],
    { allergens: GD },
  ),
  food(
    'jalebi',
    'Jalebi',
    '🌀',
    'sweet',
    'veg',
    [385, 2.5, 60, 15],
    { piece: 25 },
    'piece',
    ['jalebi', 'jilebi', 'imarti'],
    { allergens: G },
  ),
  food(
    'rasgulla',
    'Rasgulla',
    '⚪',
    'sweet',
    'veg',
    [186.5, 4, 37, 2.5],
    { piece: 50 },
    'piece',
    ['rasgulla', 'rosogolla', 'rasagola', 'rasmalai'],
    { allergens: D },
  ),
  food(
    'kheer',
    'Kheer',
    '🍮',
    'sweet',
    'veg',
    [141, 4, 20, 5],
    { bowl: 150, katori: 100 },
    'katori',
    ['kheer', 'payasam', 'rice pudding', 'phirni', 'seviyan', 'sheer khurma'],
    { allergens: D },
  ),
  food(
    'halwa',
    'Halwa',
    '🟧',
    'sweet',
    'veg',
    [302, 4, 40, 14],
    { bowl: 100, katori: 100, serving: 100 },
    'katori',
    ['halwa', 'sheera', 'sooji halwa', 'suji halwa', 'gajar halwa', 'kesari', 'moong dal halwa'],
    { allergens: GD },
  ),
  food(
    'ladoo',
    'Ladoo',
    '🟠',
    'sweet',
    'veg',
    [479, 9, 50, 27],
    { piece: 40 },
    'piece',
    ['ladoo', 'laddu', 'besan ladoo', 'motichoor ladoo', 'boondi ladoo'],
    { allergens: D },
  ),
  food(
    'barfi',
    'Barfi',
    '🟫',
    'sweet',
    'veg',
    [427, 9, 55, 19],
    { piece: 25 },
    'piece',
    ['barfi', 'burfi', 'kaju katli', 'mithai', 'peda', 'sweet', 'sandesh'],
    { allergens: D },
  ),
  food(
    'chocolate',
    'Milk chocolate',
    '🍫',
    'sweet',
    'veg',
    [535, 7.7, 59.4, 29.7],
    { piece: 10, serving: 40 },
    'serving',
    ['chocolate', 'dairy milk', 'chocolate bar', 'milk chocolate', 'kitkat', 'chocolates'],
    { allergens: D, source: 'usda' },
  ),
  food(
    'dark_chocolate',
    'Dark chocolate',
    '🍫',
    'sweet',
    'vegan',
    [598, 7.8, 45.9, 42.6],
    { piece: 10, serving: 30 },
    'serving',
    ['dark chocolate'],
    { source: 'usda' },
  ),
  food(
    'cake',
    'Cake / pastry',
    '🍰',
    'sweet',
    'egg',
    [373, 5, 50, 17],
    { slice: 80, piece: 80 },
    'slice',
    ['cake', 'pastry', 'cupcake', 'brownie', 'muffin', 'birthday cake'],
    { allergens: ['gluten', 'dairy', 'egg'] },
  ),
  food(
    'sugar',
    'Sugar',
    '🍬',
    'sweet',
    'vegan',
    [387, 0, 100, 0],
    { tsp: 4, tbsp: 12.5 },
    'tsp',
    ['sugar', 'cheeni', 'shakkar'],
    { source: 'usda' },
  ),
  food(
    'jaggery',
    'Jaggery',
    '🟫',
    'sweet',
    'vegan',
    [383, 0.4, 95, 0.1],
    { piece: 10, tsp: 5 },
    'piece',
    ['jaggery', 'gur', 'gud'],
  ),
  food(
    'honey',
    'Honey',
    '🍯',
    'sweet',
    'veg',
    [304, 0.3, 82.4, 0],
    { tsp: 7, tbsp: 21 },
    'tsp',
    ['honey', 'shahad'],
    { jainAvoid: true, source: 'usda' },
  ),
  food(
    'jam',
    'Jam',
    '🍓',
    'sweet',
    'vegan',
    [278, 0.4, 69, 0.1],
    { tsp: 7, tbsp: 20 },
    'tbsp',
    ['jam', 'fruit jam', 'kissan jam', 'marmalade'],
    { source: 'usda' },
  ),

  // ── Beverages ────────────────────────────────────────────────────────────
  food(
    'chai',
    'Tea with milk & sugar',
    '☕',
    'beverage',
    'veg',
    [40.7, 1.2, 6.5, 1.1],
    { cup: 150, glass: 200 },
    'cup',
    [
      'tea',
      'chai',
      'masala chai',
      'milk tea',
      'tea with milk',
      'cutting chai',
      'adrak chai',
      'ginger tea',
      'elaichi chai',
    ],
    { allergens: D, liquid: true },
  ),
  food(
    'coffee_milk',
    'Coffee with milk & sugar',
    '☕',
    'beverage',
    'veg',
    [45.5, 1.5, 6.5, 1.5],
    { cup: 150, glass: 250 },
    'cup',
    [
      'coffee',
      'filter coffee',
      'cappuccino',
      'latte',
      'nescafe',
      'milk coffee',
      'kaapi',
      'coffee with milk',
    ],
    { allergens: D, liquid: true },
  ),
  food(
    'cold_coffee',
    'Cold coffee',
    '🧋',
    'beverage',
    'veg',
    [69.8, 2.5, 10, 2.2],
    { glass: 250, cup: 200 },
    'glass',
    ['cold coffee', 'iced coffee', 'frappe', 'frappuccino'],
    { allergens: D, liquid: true },
  ),
  food(
    'black_coffee',
    'Black coffee',
    '☕',
    'beverage',
    'vegan',
    [2, 0.1, 0, 0],
    { cup: 150 },
    'cup',
    ['black coffee', 'americano', 'espresso', 'coffee without sugar'],
    { liquid: true, source: 'usda' },
  ),
  food(
    'green_tea',
    'Green / black tea (no milk)',
    '🍵',
    'beverage',
    'vegan',
    [1, 0, 0.2, 0],
    { cup: 200 },
    'cup',
    ['green tea', 'black tea', 'lemon tea', 'herbal tea', 'kahwa'],
    { liquid: true },
  ),
  food(
    'milkshake',
    'Milkshake',
    '🥤',
    'beverage',
    'veg',
    [81.2, 2.8, 13, 2],
    { glass: 250, cup: 200 },
    'glass',
    ['milkshake', 'banana shake', 'mango shake', 'smoothie', 'chocolate shake'],
    { allergens: D, liquid: true },
  ),
  food(
    'orange_juice',
    'Fruit juice',
    '🧃',
    'beverage',
    'vegan',
    [45, 0.7, 10.4, 0.2],
    { glass: 250, cup: 200 },
    'glass',
    ['orange juice', 'juice', 'fresh juice', 'mosambi juice', 'fruit juice', 'apple juice'],
    { liquid: true, source: 'usda' },
  ),
  food(
    'coconut_water',
    'Coconut water',
    '🥥',
    'beverage',
    'vegan',
    [19, 0.7, 3.7, 0.2],
    { glass: 250, piece: 250 },
    'glass',
    ['coconut water', 'nariyal pani', 'tender coconut', 'elaneer'],
    { liquid: true, source: 'usda' },
  ),
  food(
    'soft_drink',
    'Soft drink',
    '🥤',
    'beverage',
    'vegan',
    [41, 0, 10.6, 0],
    { glass: 250, serving: 330 },
    'glass',
    [
      'coke',
      'pepsi',
      'soda',
      'soft drink',
      'cola',
      'sprite',
      'thums up',
      'fanta',
      'cold drink',
      'limca',
    ],
    { liquid: true, source: 'usda' },
  ),
  food(
    'nimbu_pani',
    'Nimbu pani',
    '🍋',
    'beverage',
    'vegan',
    [26, 0.1, 6.5, 0],
    { glass: 250 },
    'glass',
    ['nimbu pani', 'lemonade', 'shikanji', 'lemon water', 'lime juice'],
    { liquid: true },
  ),
  food(
    'water',
    'Water',
    '💧',
    'beverage',
    'vegan',
    [0, 0, 0, 0],
    { glass: 250, cup: 200 },
    'glass',
    ['water', 'paani', 'pani'],
    { liquid: true },
  ),
  food(
    'beer',
    'Beer',
    '🍺',
    'beverage',
    'vegan',
    [43, 0.5, 3.6, 0],
    { glass: 330, serving: 330 },
    'glass',
    ['beer', 'lager', 'pint', 'ale'],
    { liquid: true, alcoholG: 3.9, source: 'usda' },
  ),
  food(
    'wine',
    'Wine',
    '🍷',
    'beverage',
    'vegan',
    [85, 0.1, 2.6, 0],
    { glass: 150 },
    'glass',
    ['wine', 'red wine', 'white wine'],
    { liquid: true, alcoholG: 10.6, source: 'usda' },
  ),

  // ── Vegetables (plain) ───────────────────────────────────────────────────
  food(
    'potato_boiled',
    'Boiled potato',
    '🥔',
    'raw_veg',
    'vegan',
    [87, 1.9, 20, 0.1],
    { piece: 150 },
    'piece',
    ['boiled potato', 'potato', 'aloo', 'baked potato'],
    { jainAvoid: true, source: 'usda' },
  ),
  food(
    'sweet_potato',
    'Sweet potato',
    '🍠',
    'raw_veg',
    'vegan',
    [76, 1.4, 17.7, 0.1],
    { piece: 130 },
    'piece',
    ['sweet potato', 'shakarkandi', 'shakarkand'],
    { jainAvoid: true, source: 'usda' },
  ),
  food(
    'cucumber',
    'Cucumber',
    '🥒',
    'raw_veg',
    'vegan',
    [15, 0.7, 3.6, 0.1],
    { piece: 200, bowl: 100, slice: 7 },
    'piece',
    ['cucumber', 'kheera', 'kakdi'],
    { source: 'usda' },
  ),
  food(
    'tomato',
    'Tomato',
    '🍅',
    'raw_veg',
    'vegan',
    [18, 0.9, 3.9, 0.2],
    { piece: 100, slice: 20 },
    'piece',
    ['tomato', 'tamatar'],
    { source: 'usda' },
  ),
  food(
    'carrot',
    'Carrot',
    '🥕',
    'raw_veg',
    'vegan',
    [41, 0.9, 9.6, 0.2],
    { piece: 60, bowl: 100 },
    'piece',
    ['carrot', 'gajar'],
    { jainAvoid: true, source: 'usda' },
  ),
  food(
    'broccoli',
    'Broccoli',
    '🥦',
    'raw_veg',
    'vegan',
    [35, 2.4, 7.2, 0.4],
    { bowl: 100, cup: 156 },
    'bowl',
    ['broccoli'],
    { source: 'usda' },
  ),
  food(
    'sweet_corn',
    'Sweet corn',
    '🌽',
    'raw_veg',
    'vegan',
    [96, 3.4, 21, 1.5],
    { piece: 100, cup: 145, bowl: 100 },
    'cup',
    ['corn', 'sweet corn', 'bhutta', 'corn cob', 'makka', 'corn chaat'],
    { source: 'usda' },
  ),
  food(
    'tofu',
    'Tofu',
    '🧊',
    'dal',
    'vegan',
    [144, 17.3, 2.8, 8.7],
    { piece: 85, serving: 100 },
    'serving',
    ['tofu', 'bean curd', 'soy paneer'],
    { allergens: ['soy'], source: 'usda' },
  ),
  food(
    'mushroom',
    'Mushrooms (cooked)',
    '🍄',
    'raw_veg',
    'vegan',
    [28, 2.2, 5.3, 0.5],
    { bowl: 100, cup: 156 },
    'bowl',
    ['mushroom', 'mushrooms', 'mushroom sabzi'],
    { jainAvoid: true, source: 'usda' },
  ),
];
